name: Publish HTML Documentation

on:
  push:
    branches:
      - "master"

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Export API docs
        run: python gen.py && mv docs/Schema/* docs

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'
      - run: |
          wget http://xsdvi.sourceforge.net/xsdvi-20080430-1405.zip
          unzip xsdvi-20080430-1405.zip -d xsdvi
          java -jar xsdvi/lib/xsdvi.jar Schema/UKRDC.xsd
          patch -p0 < collapse-nodes.patch
          mv UKRDC.svg docs/diagram.svg

      - name: Deploy API docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
